---
- name: check if epel repo is already configured
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_register_repofile

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_register_repofile.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: install epel repo
  yum_repository:
    name: "{{ epel_repo_name }}"
    file: "{{ epel_repofile_path }}"
    metalink: "{{ epel_repo_metalink_url }}"
    description: "EPEL Packages for Enterprise Linux 7 - $basearch"
    failovermethod: priority
    gpgcheck: 1
    enabled: "{{ epel_repo_enabled_by_default }}"
    state: present
